import type { Metadata } from "next";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import MantineBaseProviderClient from "@/providers/mantine/MantineBaseProvider.client";
import {Center, DirectionProvider} from "@mantine/core";
import localFont from "next/font/local";
import { I18nProviderClient } from "../../../locales/client";
import "./../globals.css";
import { EnvProvider } from "@/providers/EnvProvider";
import QueryClientProvider from "@/providers/QueryClientProvider";
import { getCurrentLocale } from "../../../locales/server";
import TailwindContainer from "@/components/shared/Container";

export const metadata: Metadata = {
	title: "DOCIES PAGE :)",
	description: "Generated by create next app",
};

const vazir = localFont({
	src: "../../fonts/vazir/Vazir.woff2",
	variable: "--font-vazir",
	display: "swap",
});

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

	// const locale = await getCurrentLocale();
	// const dir = locale === "fa" ? "rtl" : "ltr";
	//
	// console.log(dir , locale)


	return (
		<html lang={"fa"} className={vazir.variable} dir={"ltr"}>
			<body>
				{/*<I18nProviderClient locale={locale} fallback={<p>Loading...</p>}>*/}
					<DirectionProvider initialDirection={"rtl"} detectDirection={true}>
						<MantineBaseProviderClient>
							<EnvProvider
								envs={{
									baseUrl: process.env.BASE_URL,
								}}
							>
								<QueryClientProvider>
									<Center>
										{children}
									</Center>
								</QueryClientProvider>
							</EnvProvider>
						</MantineBaseProviderClient>
					</DirectionProvider>
				{/*</I18nProviderClient>*/}
			</body>
		</html>
	);
}
